chatting-app-django/ChatApp/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    # path('admin/', admin.site.urls),
    path('', include('chat.urls')),
]

chatting-app-django/chat/urls.py
from django.urls import path
from . import views
from django.contrib import admin

urlpatterns = [
    path('admin/', admin.site.urls),

    path('', views.index, name='index'),
    path('chat/', views.chat_view, name='chats'),
    path('chat/<int:sender>/<int:receiver>/', views.message_view, name='chat'),
    path('api/messages/<int:sender>/<int:receiver>/', views.message_list, name='message-detail'),
    path('api/messages/', views.message_list, name='message-list'),
    path('logout/', views.logout_user, name='logout'),
    path('register/', views.register_view, name='register'),
    path('user/', views.user, name='user'),
]

chatting-app-django/chat/models.py
from django.contrib.auth.models import User
from django.db import models
from django.contrib.auth.models import AbstractUser
from django.db.models.signals import post_save
from django.dispatch import receiver


class Profile(models.Model):
    user = models.IntegerField(blank=True)
    open_key = models.CharField(max_length=100, blank=True)
    secret_key = models.CharField(max_length=100, blank=True)
    aes_key = models.CharField(max_length=100, blank=True)


class Message(models.Model):
    sender = models.ForeignKey(User, on_delete=models.CASCADE, related_name='sender')
    receiver = models.ForeignKey(User, on_delete=models.CASCADE, related_name='receiver')
    message = models.CharField(max_length=1200)
    timestamp = models.DateTimeField(auto_now_add=True)
    is_read = models.BooleanField(default=False)

    def __str__(self):
        return self.message

    class Meta:
        ordering = ('timestamp',)

# class ChatRoom(models.Model):
#     room_name = models.CharField(max_length = 30)
#     room_size = models.IntegerField(default=5)
#     room_code = models.CharField(max_length=5)
#     members = models.ManyToManyField(User)
#     creation_date = models.DateTimeField(auto_now=True)
#
#     def __str__(self):
#         return f'{self.pk}-{self.room_name}'

chatting-app-django/chat/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from django.forms import TextInput


from django.forms import TextInput

from django.db import models
from django.forms import ModelForm, TextInput, Textarea, FileField


class SignUpForm(UserCreationForm):
    password1 = forms.CharField(widget=forms.PasswordInput(attrs={'class': 'form-control'}))
    password2 = forms.CharField(widget=forms.PasswordInput(attrs={'class': 'form-control'}))
    class Meta:
        model = User
        fields=['username','password1','password2']
        widgets = {
            'username': TextInput(attrs={'class':'form-control'}),
        }

chatting-app-django/chat/views.py
# -*- coding: utf-8 -*-

from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.models import User
from django.db.models import Q
from django.http.response import JsonResponse, HttpResponse
from django.shortcuts import render, redirect, get_object_or_404
from django.views.decorators.csrf import csrf_exempt
from django.views.generic import ListView
from rest_framework.parsers import JSONParser
from rest_framework.permissions import IsAuthenticated
from rest_framework.response import Response
from rest_framework.views import APIView
import time
from .models import Message, Profile
from .forms import *
from .serializers import MessageSerializer, UserSerializer
from . import RSA



@csrf_exempt
def index(request):
    if request.user.is_authenticated:
        return redirect('chats')
    if request.method == 'GET':
        return render(request, 'chat/index.html', {})
    if request.method == "POST":
        username, password = request.POST['username'], request.POST['password']
        user = authenticate(username=username, password=password)
        if user is not None:
            print('login OK')
            login(request, user)
        else:
            return HttpResponse('{"error": "User does not exist"}')
        return redirect('chats')


def logout_user(request):
    logout(request)
    return redirect('index')


def user(request):
    return render(request, 'chat/lk.html', {})


class SearchResultsView(ListView):
    model = User
    template_name = 'chat/search_results.html'

    def get_queryset(self):
        query = self.request.GET.get('q')
        object_list = User.objects.filter(
            Q(name__icontains=query) | Q(state__icontains=query)
        )
        return object_list


@csrf_exempt
def message_list(request, sender=None, receiver=None):
    if request.method == 'GET':
        rsa = RSA.Rsa()
        aes = RSA.Aes()
        secret_key = Profile.objects.get(user=receiver)
        messages = Message.objects.filter(sender_id=sender, receiver_id=receiver, is_read=False)
        # print(dir(messages))
        # print(type(messages))
        # messages.message = '234432342234432'
        for message in messages:
            message.message = aes.dec_aes(message.message, rsa.decript(secret_key.aes_key, secret_key.secret_key))
            message.save()

        messages = Message.objects.filter(sender_id=sender, receiver_id=receiver, is_read=False)

        serializer = MessageSerializer(messages, many=True, context={'request': request})
        print(serializer.data)

        messages1 = Message.objects.filter(sender_id=sender, receiver_id=receiver, is_read=False)
        for i in messages1:
            i.is_read = True
            i.message = aes.enc_aes(i.message, rsa.decript(secret_key.aes_key, secret_key.secret_key))
            i.save()

        print(serializer.data)

        return JsonResponse(serializer.data, safe=False)

    elif request.method == 'POST':
        data = JSONParser().parse(request)
        user_id = User.objects.get(username=data['receiver'])
        open_key = Profile.objects.get(user=user_id.id)
        rsa = RSA.Rsa()
        aes = RSA.Aes()
        open_key.save()
        data['message'] = aes.enc_aes(data['message'], rsa.decript(open_key.aes_key, open_key.secret_key))
        serializer = MessageSerializer(data=data)
        if serializer.is_valid():
            serializer.save()
            return JsonResponse(serializer.data, status=201)
        return JsonResponse(serializer.errors, status=400)


@csrf_exempt
def register_view(request):
    if request.method == 'POST':
        form = SignUpForm(request.POST)
        print(form)
        if form.is_valid():
            user = form.save(commit=False)
            username = form.data['username']
            password = form.data['password1']
            print(username, password)
            user.set_password(password)
            user.save()
            user = authenticate(username=username, password=password)
            # print(user.id, 13241234424244234)
            # Profile.objects.filter(id=user.id).update(secret_key='ddd', open_key='3123')
            rsa = RSA.Rsa()
            key = Profile()
            key.secret_key = rsa.get_secret_key()
            key.open_key = rsa.get_open_key()
            aes = RSA.Aes()
            aes_key = aes.print_key()
            key_aes_enc = rsa.encript(aes_key, rsa.get_open_key())
            key.aes_key = key_aes_enc
            key.user = int(user.id)
            key.save()
            if user is not None:
                if user.is_active:
                    login(request, user)
                    return redirect('chats')
    else:
        form = SignUpForm()
    template = 'chat/registrations.html'
    context = {'form': form}
    return render(request, template, context)


@csrf_exempt
def chat_view(request):
    if not request.user.is_authenticated:
        return redirect('index')
    if request.method == "GET":
        return render(request, 'chat/chat.html',
                      {'users': User.objects.exclude(username=request.user.username)})


@csrf_exempt
def message_view(request, sender, receiver):
    if not request.user.is_authenticated:
        return redirect('index')
    if request.method == "GET":
        rsa = RSA.Rsa()
        aes = RSA.Aes()
        secret_key1 = Profile.objects.get(user=receiver)
        secret_key2 = Profile.objects.get(user=sender)

        list1 = [(aes.dec_aes(i.message, rsa.decript(secret_key1.aes_key, secret_key1.secret_key)), 1, i.timestamp.strftime("%m-%d %H.%M")) for i in Message.objects.filter(sender_id=sender, receiver_id=receiver)]
        list2 = [(aes.dec_aes(i.message, rsa.decript(secret_key2.aes_key, secret_key2.secret_key)), 0, i.timestamp.strftime("%m-%d %H.%M")) for i in Message.objects.filter(sender_id=receiver, receiver_id=sender)]
        a = sorted(list2+list1, key=lambda x: x[-1])
        for i in range(len(a)):
            b = (str(a[i][0]).replace("<p>", "").replace("</p>", ""), a[i][1], a[i][2])
            a[i] = b

        # qwerty = Message.objects.filter(sender_id=sender, receiver_id=receiver)
        return render(request, "chat/messages.html",
                      {'users': User.objects.exclude(username=request.user.username),
                       'receiver': User.objects.get(id=receiver),
                       'messages': a})

# class GetOrCreateRoomApi(APIView):
#
#     permission_classes = (IsAuthenticated,)
#
#     # get the rooms in which the user is enrolled
#     def get(self, request):
#         user = self.get_user(request)
#         rooms = user.chatroom_set.all()
#         serializer = ChatRoomSerializer(rooms, many=True)
#         # serializer.is_valid(raise_exception=True)
#         return Response(serializer.data)
#
#
#     def post(self, request):
#         serializer = ChatRoomSerializer(data=request.data)
#         serializer.is_valid(raise_exception=True)
#         serializer.save()
#         return Response(serializer.data)
#
# class JoinRoomApi(APIView):
#
#     permission_classes = (IsAuthenticated,)
#
#     def post(self, request):
#         serializer = AddUserToRoomSerializer(data=request.data)
#         serializer.is_valid(raise_exception=True)
#         res = serializer.save()
#         if res is None:
#             return Response({"error":"Can not Register You to Room"})
#         return Response(serializer.data)

chatting-app-django/templates/chat/chat.html
<!DOCTYPE HTML>
{% extends 'chat/chats.html' %}
{% block content %}
<head>
      <!--Import Google Icon Font-->
        <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet" media="screen">
<!--        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">-->
        <!--Import materialize.css-->
        <link rel="stylesheet" href="/static/css/materialize.css"  media="screen,projection"/>
        <link rel="stylesheet" href="/static/css/style.css"  media="screen,projection"/>

      <!--Let browser know website is optimized for mobile-->
        <meta name="viewport" content="width=device-width, initial-scale=1.0"/>

      <!--Import jQuery before materialize.js-->
        <script type="text/javascript" src="https://code.jquery.com/jquery-3.2.1.min.js"></script>
        <script type="text/javascript" src="/static/js/materialize.min.js"></script>
        <script type="text/javascript" src="/static/js/chat.js"></script>
        <script src="https://cdn.tiny.cloud/1/no-api-key/tinymce/5/tinymce.min.js" referrerpolicy="origin"></script>
    </head>
<style>
        .module {
  all: unset;
}
 </style>

    <div class="section" style="height: 80vh; background-color: #0E1621;">
    <div class="row" style="background-color: #0E1621; border-radius: 10px;">
        <div class="col s3" style="background-color: #0E1621; border-radius: 10px;">
        <div class="card" style="background-color: #0E1621; border-radius: 10px;">
            <form action="{% url 'chats' %}" method="get" style="">
                <input id="select" style="background-color: #0E1621; color: #ffffff; font-size: 15px;" name="q" type="text" placeholder="Введите id друга..." >
            </form>
            <div class="collection" style="border-color: #0E1621; border-radius: 10px; background-color: #0E1621; color: #fffff;">
                {% block users %}
                {% for user in users %}
                <ul id="list" style="border-radius: 10px;">
                    <li class="element" style="border-radius: 30px;"><a href="{% url 'chat' request.user.id user.id %}" id="user{{ user.id }}" class="collection-item row" style="border-radius: 10px; color: #fffff;">
                        <div class="col s8" style="border-radius: 10px; color: #fffff;">
                        <span class="title" style="font-weight: bolder; border-radius: 10px; color: #fffff;">{{ user }}</span>
                        </div>
                    </a></li>
                </ul>
                {% endfor %}
                {% endblock %}
            </div>
        </div>
        </div>
        <div class="col s9" style="border-radius: 25px;">
            <div class="card" style="border-radius: 25px; background-color: #0E1621;">
            <div id="board" class="section grey lighten-3" style="background-color: #0E1621; height: 68vh; padding: 5px; overflow-y: scroll; border-radius: 25px;">
                {% block messages %}

                {% endblock %}
            </div>

            <form id="chat-box" class="form-group {% block hide %}hide{% endblock %}" method="post">
                {% csrf_token %}
                <div class="row" style="color: #0E1621;">
                    <div class="col s11">
                        <div class="input-field" style="background-color: #0E1621;">
                            <input id="id_message">
                        </div>
                    </div>
                        <button class="btn btn-floating black lighten-2 waves-effect waves-light"><i class="material-icons">send</i></button>
                </div>
            </form>
            </div>
        </div>
    </div>
    </div>
    {% load static %}
    <script>
tinymce.init({
  selector: '#id_message',
  skin: 'oxide-dark',
  height: '150px',
  content_css: 'dark',
  statusbar: false,
  plugins: 'emoticons image media',
  toolbar: 'emoticons | link image | media',
  video_template_callback: function(data) {
   return '<video width="' + data.width + '" height="' + data.height + '"' + (data.poster ? ' poster="' + data.poster + '"' : '') + ' controls="controls">\n' + '<source src="' + data.source + '"' + (data.sourcemime ? ' type="' + data.sourcemime + '"' : '') + ' />\n' + (data.altsource ? '<source src="' + data.altsource + '"' + (data.altsourcemime ? ' type="' + data.altsourcemime + '"' : '') + ' />\n' : '') + '</video>';
 },
  // enable title field in the Image dialog
  menubar: false,
  image_title: true,
  // enable automatic uploads of images represented by blob or data URIs
  automatic_uploads: true,
  // add custom filepicker only to Image dialog
  file_picker_types: 'image',
  file_picker_callback: function(cb, value, meta) {
    var input = document.createElement('input');
    input.setAttribute('type', 'file');
    input.setAttribute('accept', 'image/*');

    input.onchange = function() {
      var file = this.files[0];
      var reader = new FileReader();

      reader.onload = function () {
        var id = 'blobid' + (new Date()).getTime();
        var blobCache =  tinymce.activeEditor.editorUpload.blobCache;
        var base64 = reader.result.split(',')[1];
        var blobInfo = blobCache.create(id, file, base64);
        blobCache.add(blobInfo);

        // call the callback and populate the Title field with the file name
        cb(blobInfo.blobUri(), { title: file.name });
      };
      reader.readAsDataURL(file);
    };

    input.click();
  }
});
</script>
    <script src="{% static 'js/chat.js' %}"></script>
    <script>
        // For receiving
        sender_id = "{{ receiver.id }}";
        receiver_id = "{{ request.user.id }}";

        //For sending
        $(function () {
            scrolltoend();
            $('#chat-box').on('submit', function (event) {
                event.preventDefault();
                var message = $('#id_message');
                send('{{ request.user.username }}', '{{ receiver.username }}', message.val());
                message.val('');
            })
        })

     $(document).ready(function() {
    var $elements = $('#list .element');
    $('#select').on('keyup input', function() {
        var value = this.value;
        $elements.hide();
        $elements.filter(':contains("' + value + '")').show();
    });
    });
    </script>
{% endblock %}

chatting-app-django/templates/chat/chats.html
{% load static %}
  <style>
   ul.hr {
    margin: 0; /* Обнуляем значение отступов */
    padding: 4px; /* Значение полей */
   }
   ul.hr li {
    display: inline; /* Отображать как строчный элемент */
    margin-right: 5px; /* Отступ слева */
   }
   button {
    background-color: #17212B;
    border: none;
   }
  </style>

<!DOCTYPE html>
<html style="font-size: 16px;">
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta charset="utf-8">
    <meta name="keywords" content="">
    <meta name="description" content="">
    <meta name="page_type" content="np-template-header-footer-from-plugin">

    <title>Чаты</title>
      <link rel="shortcut icon" href="/static/img/утка.png" type="image/png">

    <link rel="stylesheet" href="/static/css/nicepage.css" media="screen">
<link rel="stylesheet" href="/static/css/Регистрация.css" media="screen">
    <script class="u-script" type="text/javascript" src="/static/js/jquery.js" defer=""></script>
    <script class="u-script" type="text/javascript" src="/static/js/nicepage.js" defer=""></script>
    <meta name="generator" content="Nicepage 3.16.0, nicepage.com">
    <link id="u-theme-google-font" rel="stylesheet" href="https://fonts.googleapis.com/css?family=Open+Sans:300,300i,400,400i,600,600i,700,700i,800,800i|Cambay:400,400i,700,700i">


    <script type="application/ld+json">{
		"@context": "http://schema.org",
		"@type": "Organization",
		"name": "",
		"url": "index.html",
		"logo": "/static/img/S.png"
}</script>
    <meta property="og:title" content="О нас">
    <meta property="og:type" content="website">
    <meta name="theme-color" content="#5595e8">
    <link rel="canonical" href="index.html">
    <meta property="og:url" content="index.html">
  </head>
  <body class="u-body"><header><div class="u-clearfix u-sheet u-valign-middle-xl u-sheet-1">


    <div class="nav-wrapper container" style="margin-left: 1000px;margin-down:10px;">
        <ul class="hr">
          <li><a style="color: #fffff;font-size: 40px;padding-right:40px;" >{{ request.user.username }}</a></li>
          <li><a href="{% url 'logout' %}"><i class="material-icons">power_settings_new</i></a></li>
      </ul>
    </div>

          <div class="u-custom-menu u-nav-container-collapse">
            <div class="u-black u-container-style u-inner-container-layout u-opacity u-opacity-95 u-sidenav">
              <div class="u-inner-container-layout u-sidenav-overflow">
                <div class="u-menu-close"></div>
              </div>
            </div>
            <div class="u-black u-menu-overlay u-opacity u-opacity-70"></div>
          </div>
      </div></header>

<div class="content container">
        <div class="row">
            <div class="col-md-8">
            {% block content %}
            {% endblock %}
            </div>
        </div>
    </div>
    </body>
</html>

chatting-app-django/templates/chat/ddd.html
{% load static %}
  <style>
   ul.hr {
    margin: 0; /* Обнуляем значение отступов */
    padding: 4px; /* Значение полей */
   }
   ul.hr li {
    display: inline; /* Отображать как строчный элемент */
    margin-right: 5px; /* Отступ слева */
   }
   button {
    background-color: #17212B;
    border: none;
   }
  </style>

<!DOCTYPE html>
<html style="font-size: 16px;">
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta charset="utf-8">
    <meta name="keywords" content="">
    <meta name="description" content="">
    <meta name="page_type" content="np-template-header-footer-from-plugin">

    <title>Регистрация</title>
      <link rel="shortcut icon" href="/static/img/утка.png" type="image/png">

    <link rel="stylesheet" href="/static/css/nicepage.css" media="screen">
<link rel="stylesheet" href="/static/css/Регистрация.css" media="screen">
    <script class="u-script" type="text/javascript" src="/static/js/jquery.js" defer=""></script>
    <script class="u-script" type="text/javascript" src="/static/js/nicepage.js" defer=""></script>
    <meta name="generator" content="Nicepage 3.16.0, nicepage.com">
    <link id="u-theme-google-font" rel="stylesheet" href="https://fonts.googleapis.com/css?family=Open+Sans:300,300i,400,400i,600,600i,700,700i,800,800i|Cambay:400,400i,700,700i">


    <script type="application/ld+json">{
		"@context": "http://schema.org",
		"@type": "Organization",
		"name": "",
		"url": "index.html",
		"logo": "/static/img/S.png"
}</script>
    <meta property="og:title" content="О нас">
    <meta property="og:type" content="website">
    <meta name="theme-color" content="#5595e8">
    <link rel="canonical" href="index.html">
    <meta property="og:url" content="index.html">
  </head>
  <body class="u-body"><header class="u-clearfix u-custom-color-2 u-header u-header" id="sec-d9ff"><div class="u-clearfix u-sheet u-valign-middle-xl u-sheet-1">
          <img src="/static/img/утка.png" class="u-logo-image u-logo-image-1" width="80" style="padding-top: 20px">


    <div class="nav-wrapper container" style="margin-left: 1000px;margin-down:40px;">
        <ul class="hr">
          <li><a href="{%url 'user'%}" style="color: #fffff;font-size: 40px;padding-right:40px;" >{{ request.user.username }}</a></li>
          <li><a href="{% url 'logout' %}"><i class="material-icons">power_settings_new</i></a></li>
      </ul>
    </div>

          <div class="u-custom-menu u-nav-container-collapse">
            <div class="u-black u-container-style u-inner-container-layout u-opacity u-opacity-95 u-sidenav">
              <div class="u-inner-container-layout u-sidenav-overflow">
                <div class="u-menu-close"></div>
              </div>
            </div>
            <div class="u-black u-menu-overlay u-opacity u-opacity-70"></div>
          </div>
      </div></header>

<div class="content container">
        <div class="row">
            <div class="col-md-8">
            {% block content %}
            {% endblock %}
            </div>
        </div>
    </div>
    </body>
</html>

chatting-app-django/templates/chat/index.html
<!DOCTYPE html>
<html style="font-size: 16px;">
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta charset="utf-8">
    <meta name="keywords" content="">
    <meta name="description" content="">
    <meta name="page_type" content="np-template-header-footer-from-plugin">

    <title>Вход</title>
      <link rel="shortcut icon" href="/static/img/утка.png" type="image/png">

    <link rel="stylesheet" href="/static/css/nicepage.css" media="screen">
<link rel="stylesheet" href="/static/css/Регистрация.css" media="screen">
    <script class="u-script" type="text/javascript" src="/static/js/jquery.js" defer=""></script>
    <script class="u-script" type="text/javascript" src="/static/js/nicepage.js" defer=""></script>
    <meta name="generator" content="Nicepage 3.16.0, nicepage.com">
    <link id="u-theme-google-font" rel="stylesheet" href="https://fonts.googleapis.com/css?family=Open+Sans:300,300i,400,400i,600,600i,700,700i,800,800i|Cambay:400,400i,700,700i">
    
    
    <script type="application/ld+json">{
		"@context": "http://schema.org",
		"@type": "Organization",
		"name": "",
		"url": "index.html",
		"logo": "/static/img/S.png"
}</script>
    <meta property="og:title" content="О нас">
    <meta property="og:type" content="website">
    <meta name="theme-color" content="#5595e8">
    <link rel="canonical" href="index.html">
    <meta property="og:url" content="index.html">
  </head>
  <body class="u-body"><header><div class="u-clearfix u-sheet u-valign-middle-xl u-sheet-1">

        <nav class="u-menu u-menu-dropdown u-offcanvas u-menu-1" data-responsive-from="XL">
          <div class="menu-collapse" style="font-size: 1rem; letter-spacing: 0px; font-weight: 700; text-transform: uppercase;">
            <a class="u-button-style u-custom-active-border-color u-custom-border u-custom-border-color u-custom-borders u-custom-hover-border-color u-custom-left-right-menu-spacing u-custom-padding-bottom u-custom-text-color u-custom-text-hover-color u-custom-top-bottom-menu-spacing u-nav-link u-text-active-palette-1-base u-text-hover-palette-2-base" href="#">
              <svg class="u-svg-link" viewBox="0 0 24 24"><use xmlns:xlink="http://www.w3.org/1999/xlink" xlink:href="#menu-hamburger"></use></svg>
              <svg class="u-svg-content" version="1.1" id="menu-hamburger" viewBox="0 0 16 16" x="0px" y="0px" xmlns:xlink="http://www.w3.org/1999/xlink" xmlns="http://www.w3.org/2000/svg"><g><rect y="1" width="16" height="2"></rect><rect y="7" width="16" height="2"></rect><rect y="13" width="16" height="2"></rect>
</g></svg>
            </a>
          </div>

          <div class="u-custom-menu u-nav-container-collapse">
            <div class="u-black u-container-style u-inner-container-layout u-opacity u-opacity-95 u-sidenav">
              <div class="u-inner-container-layout u-sidenav-overflow">
                <div class="u-menu-close"></div>
                <ul class="u-align-center u-nav u-popupmenu-items u-unstyled u-nav-2"><li class="u-nav-item"><a class="u-button-style u-nav-link" href="/" style="padding: 10px 20px;">Главная</a>
</li><li class="u-nav-item"><a class="u-button-style u-nav-link" href="/log" style="padding: 10px 20px;">Войти</a>
</li><li class="u-nav-item"><a class="u-button-style u-nav-link" href="/reg" style="padding: 10px 20px;">Регистрация</a>
</li></ul>
              </div>
            </div>
            <div class="u-black u-menu-overlay u-opacity u-opacity-70"></div>
          </div>
        </nav>
      </div></header>
    <section class="u-align-center u-clearfix u-section-1" id="carousel_08f1">
      <div class="u-clearfix u-sheet u-sheet-1">
        <div class="u-clearfix u-expanded-width u-layout-wrap u-layout-wrap-1">
          <div class="u-layout">
            <div class="u-layout-row">
              <div class="u-align-center u-container-style u-layout-cell u-size-30 u-layout-cell-1">
                <div class="u-container-layout u-container-layout-1">
                  <img class="u-image u-image-contain u-image-default u-image-1" src="/static/img/утка2.png" alt="" data-image-width="700" data-image-height="500">
                </div>
              </div>
              <div class="u-align-center u-container-style u-layout-cell u-palette-4-base u-radius-50 u-shape-round u-size-30 u-layout-cell-2">
                <div class="u-container-layout u-container-layout-2">
                  <div class="u-form u-login-control u-radius-50 u-white u-form-1">

                    <form method="POST" class="u-clearfix u-form-custom-backend u-form-spacing-40 u-form-vertical u-inner-form" source="custom" name="form" style="padding: 30px;">
                      <div class="u-form-group u-form-name">
                        <label for="username-a30d" class="u-label">Имя</label>
                        <input type="text" placeholder="Введите Ваше Имя" id="username-a30d" name="username" class="u-border-1 u-border-grey-30 u-input u-input-rectangle u-input-1" required="">
                      </div>
                      <div class="u-form-group u-form-password">
                        <label for="password-a30d" class="u-label">Пароль</label>
                        <input type="text" placeholder="Введите пароль" id="password-a30d" name="password" class="u-border-1 u-border-grey-30 u-input u-input-rectangle u-input-2" required="">
                      </div>

                        <div class="u-align-left u-form-group u-form-submit" data-method="POST">
                            <button type="submit" class="btn blue waves-effect waves-light pull-s12" style="background: #008EB0; color: #fff; border: none; padding: 0.7rem 4rem;">Войти</button>
                        </div>

                        <div class="u-form-group u-form-reg">
                                <a href="{% url 'register' %}" class="link">Регистрация</a>
                        </div>

                      <input type="hidden" value="" name="recaptchaResponse">
                    </form>

                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </section>
  </body>
</html>